export const charsToReplace = [{ actualValue: "â", replacedValue: "a" },
{ actualValue: "ê", replacedValue: "e" },
{ actualValue: "î", replacedValue: "i" },
{ actualValue: "ô", replacedValue: "o" },
{ actualValue: "û", replacedValue: "u" },
{ actualValue: "é", replacedValue: "e" },
{ actualValue: "à", replacedValue: "a" },
{ actualValue: "è", replacedValue: "e" },
{ actualValue: "ù", replacedValue: "u" },
{ actualValue: "ç", replacedValue: "c" },
{ actualValue: "ç", replacedValue: "c" },
{ actualValue: "ä", replacedValue: "a" },
{ actualValue: "ë", replacedValue: "e" },
{ actualValue: "ï", replacedValue: "i" },
{ actualValue: "ü", replacedValue: "u" },
{ actualValue: "œ", replacedValue: "o" },
{ actualValue: "'", replacedValue: "-" },
{ actualValue: " ", replacedValue: "-" },
{ actualValue: "/", replacedValue: "-" },
];