import React, { Fragment } from 'react';
import Layout from '../app/components/Layout';
import Head from 'next/head';
class TermConditions extends React.Component {
    render() {
        return (
            <Layout>
                <Head>
                    <meta property="og:title" content="Trouvez l’entreprise qui vous convient" />
                    <meta property="og:image" content="https://opsoestorage.blob.core.windows.net/companybackground-stg/spin-preview.png" />
                    <meta property="og:image:width" content="200" />
                    <meta property="og:image:height" content="200" />
                    <meta property="og:type" content="website" />
                    <meta property="og:url" content="https://www.spincv.com/" />
                </Head>
                <Fragment>
                    <div className="careerfy-subheader careerfy-subheader-with-bg">
                        <span className="careerfy-banner-transparent"></span>
                        <div className="container">
                            <div className="row">
                                <div className="col-md-12">
                                    <div className="careerfy-page-title">
                                        <h1>Termes et conditions</h1>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="careerfy-main-content">
                        <div className="container">
                            <p><strong>I. Introduction</strong><br /><br />
            Les présentes modalités de service (de l'entente) sont conclues à la date de signature ou d'acceptation en ligne (de la date d'entrée en vigueur) entre vous et OpSoE Inc., dont le siège social est situé à Montréal, Québec, Canada (ci-après appelé "SPINCV").<br /><br />
            Lorsque vous accédez ou utilisez les services en ligne et les sites internet de SPINCV, en particulier les services disponibles sur http://www.spincv.com (le "Site"), et/ou lors de la signature du présent Contrat, et/ou en acceptant ce contrat en ligne en cliquant sur une case d'acceptation, vous déclarez que vous avez lu et compris et accepté d'être joint à la politique de confidentialité de SPINCV (disponible sur http://www.spincv.com/privacy), et que vous acceptez les termes et conditions de cet accord.<br />
            Toute référence à "SPINCV" ou écrite sous le prénom de "nous" dans le présent Contrat désigne l'entité applicable comme indiquée ci-dessus, et/ou ses sociétés affiliées, filiales, employés, dirigeants, directeurs, sous-traitants, agents, partenaires ou représentants, selon le contexte. Toute référence à "Vous" ou "Votre" se référera à la personne ou entité qui conclut le présent Contrat avec SPINCV, tel qu'identifié soit par Votre information entrée lorsque Vous avez accepté en ligne ou Votre nom et informations à la fin de cet Accord. Si vous êtes un particulier qui conclut le présent contrat pour le compte d'une société ou d'un autre organisme enregistré (entité légale), vous déclarez et garantissez que vous avez la capacité et l'autorité de conclure la présente entente au nom de la personne morale, et par la présente accepter d'être lié par les termes du présent accord au nom de cette entité juridique.<br />
            Le Site est mis à la disposition exclusive des personnes à la recherche d'un emploi (Demandeurs d'emploi), par des individus et/ou organisations cherchant à fournir des informations sur les offres d'emploi, en leur nom ou pour le compte d'autrui d'agences pour des partis multiples ("employeurs"). Si vous accédez ou utilisez le site dans votre capacité à titre d'employeur ou d'autre représentant d'un employeur, vous acceptez le présent accord au nom de vous et de l'employeur, selon le cas, et vous déclarez et garantissez que vous avez le pouvoir de lier employeur, selon le cas, à la présente convention. Les demandeurs d'emploi et les employeurs peuvent être désignés collectivement comme des "utilisateurs". <br />
            Nous pouvons modifier le présent Contrat en vous notifiant ces modifications par tout moyen raisonnable, y compris en publiant un Contrat révisé sur le Site. De tels changements ne s'appliqueront pas à toute réclamation déposée avant la date à laquelle nous avons publié l'accord révisé incorporant de tels changements, ou autrement nous vous aviserons de tels changements. Votre accès au Site ou son utilisation à la suite de toute modification du présent Contrat constitueront Votre acceptation de ces modifications. Nous pouvons, à tout moment et sans responsabilité, modifier ou interrompre tout ou une partie du Site (y compris l'accès au Site via des liens tiers); facturer, modifier ou annuler les frais requis pour utiliser le site; ou offrir des opportunités à certains ou à tous les utilisateurs du site.
         </p>
                            <br />
                            <p>
                                <strong>II. Conditions d'utilisation</strong><br /><br />
            Les informations et autres caractéristiques du Site ne peuvent être utilisées que par des personnes recherchant un emploi et/ou des informations sur leur carrière et par des Employeurs à la recherche d'employés. Votre utilisation du Site est également soumise à tout autre contrat que vous pourriez avoir avec SPINCV. En cas de conflit entre cet accord et tout contrat que vous avez avec SPINCV, les termes de votre contrat prévaudront. Le terme "poste" tel qu'utilisé ici signifie les informations que vous soumettez, publiez ou affichez sur un site SPINCV.<br />
            Vous acceptez de ne pas transmettre à SPINCV ou de télécharger sur ou via le Site (que ce soit en tant que Contenu Utilisateur ou autrement) tout code Nocif, ou d'utiliser ou de détourner le Site pour votre propre profit commercial. "Code nuisible" désigne tout logiciel (parfois appelé "virus", "vers", "chevaux de Troie", "bombes à retardement", "verrous temporels", "dispositifs morts", "pièges", "codes d'accès", " un programme qui recherche et supprime les messages spécifiés des groupes de discussion Internet. '' et les " dispositifs de trappe ") qui: a) est conçu pour endommager, perturber, désactiver, nuire, gêner, interférer, intercepter, exproprier ou entraver de quelque manière que ce soit, toute donnée, support de stockage, programme, système, équipement ou communication, sur la base de tout événement, y compris par exemple (i) dépassement d'un nombre d'exemplaires, (ii) dépassement d'un nombre d'utilisateurs (iii) passage d'une période de temps, (iv) avancement à une date particulière ou un autre chiffre, ou (v) l'utilisation d'une certaine caractéristique; ou (b) permettrait à une personne non autorisée de provoquer un tel résultat; ou (c) permettrait à une personne non autorisée d'accéder aux informations d'une autre personne sans la connaissance et la permission de cette autre personne.<br />
            Tous les utilisateurs acceptent de ne pas: <br />
            (a) transmettre, afficher, distribuer, stocker ou détruire du contenu, y compris, sans s'y limiter, du Contenu SPINCV, en violation de toute loi ou règlement applicable, y compris, mais non limité aux lois ou règlements régissant la collecte, le traitement ou le transfert de renseignements personnels; en violation de la politique de confidentialité de SPINCV;<br />
            (b) prendre toute mesure qui impose une charge déraisonnable ou disproportionnée sur toute infrastructure SPINCV;<br />
            (c) utiliser des méthodes d'extraction de données, des robots ou des méthodes similaires de collecte ou d'extraction de données;<br />
            (d) violer ou tenter de violer la sécurité du Site, y compris tenter de sonder, scanner ou tester la vulnérabilité d'un système ou d'un réseau ou violer les mesures de sécurité ou d'authentification sans autorisation appropriée;<br />
            (e) falsifier tout en-tête de paquet TCP / IP ou toute partie de l'information d'en-tête dans un message électronique ou un groupe de discussion;<br />
            (f) encadrer ou créer un lien vers tout contenu ou toute information disponible sur le Site, sauf si cela est autorisé par le présent Contrat;<br />
            (g) afficher tout contenu ou matériel qui encourage ou approuve des informations fausses ou trompeuses ou des activités illégales, ou approuve ou fournit des informations pédagogiques sur des activités illégales ou d'autres activités interdites par le présent Accord, tels que la fabrication ou l'achat d'armes illégales; ou créer des virus informatiques ou des médias de piratage;<br />
            (h) afficher tout curriculum vitae ou profil ou postuler à un emploi sur le compte d'un autre parti;<br />
            (i) reporter tout contact d'un employeur à un agent, un organisme ou une autre tierce partie;<br />
            (j) mettre plus d'une copie du même curriculum vitae à la disposition du public en même temps;<br />
            (k) partager avec un tiers les identifiants de connexion au Site;<br />
            (l) accéder à des données qui ne vous sont pas destinées ou se connecter à un serveur ou un compte auquel vous n'êtes pas autorisé à accéder;<br />
            (m) afficher ou soumettre au Site toute information biographique incomplète, fausse ou inexacte ou toute information qui n'est pas la vôtre;<br />
            (n) publier du contenu qui contient des pages d'accès restreintes ou mots de passe, ou des pages ou images cachées;<br />
            (o) solliciter des mots de passe ou des informations personnellement identifiables d'autres utilisateurs;<br />
            (p) supprimer ou modifier tout document publié par une autre personne ou entité;<br />
            (q) harcelez, incitez au harcèlement ou préconisez le harcèlement de tout groupe, entreprise ou individu;<br />
            (r) envoyer des courriers ou des courriels non sollicités, faire des appels téléphoniques non sollicités ou envoyer des télécopies non sollicitées faisant la promotion et/ou la publicité de produits ou services à un utilisateur, ou contacter les utilisateurs qui ont spécifiquement demandé de ne pas être contactés par vous;<br />
            (s) tenter d'interférer avec le service à tout utilisateur, hôte ou réseau, y compris, sans s'y limiter, en soumettant un virus au site, en surchargeant, " Inondation "," publipostage excessif "," bombardement de courriers'', "ou "effondrement ";<br />
            (t) promouvoir ou approuver une copie illégale ou non autorisée du travail protégé par une autre personne, par exemple en fournissant ou en mettant à disposition des programmes informatiques piratés ou des liens, en fournissant ou en mettant à disposition des informations pour contourner les dispositifs de protection contre la copie; mise à disposition de musique piratée ou d'autres médias ou de liens vers de la musique piratée ou d'autres fichiers multimédias; ou<br />
            (u) utiliser le Site à des fins illicites ou illégales, ou publier ou soumettre tout contenu, résumé ou offre d'emploi qui est diffamatoire, diffamatoire, implicite ou explicite offensant, vulgaire, obscène, menaçant, abusif, haineux, raciste, discriminatoire, de caractère menaçant ou susceptible de causer de la gêne, des désagréments, de l'embarras, de l'anxiété ou de causer du harcèlement à toute personne ou d'inclure des liens vers des documents pornographiques, indécents ou sexuellement explicites, selon la discrétion de SPINCV.<br />
            Les violations de la sécurité du système ou du réseau peuvent entraîner une responsabilité civile et/ou pénale. SPINCV enquêtera sur les événements pouvant impliquer de telles violations et pourra impliquer et coopérer avec les autorités répressives dans la poursuite des Utilisateurs qui sont impliqués dans de telles violations.<br />
            Vous êtes responsable du maintien de la confidentialité de votre compte, Profil et mots de passe, selon le cas. Vous ne pouvez pas partager votre mot de passe ou d'autres informations d'accès au compte avec une autre partie, temporairement ou définitivement, et vous serez responsable de toutes les utilisations de vos enregistrements et mots de passe, que vous ayez autorisé ou non. Vous acceptez d'informer immédiatement SPINCV de toute utilisation non autorisée de votre compte, de votre profil ou de vos mots de passe.<br />
            SPINCV se réserve le droit d'utiliser tout Contenu Utilisateur (y compris le contenu de messages ou de matériel envoyés via ou sur le Site) pour empêcher des activités potentiellement illégales ou délictueuses, ou toute autre activité préjudiciable aux autres utilisateurs. SPINCV se réserve le droit d'utiliser une variété de méthodes pour détecter et bloquer l'activité anormale ci-dessus et pour filtrer le Contenu Utilisateur afin d'éviter les abus tels que le pourriel ou la fraude. Si vous utilisez le site, vous consentez à ce que SPINCV applique ces règles, ce qui peut entraîner une suspension temporaire ou définitive de votre compte ou l'utilisation de certaines fonctions du site, pour certains utilisateurs, avec ou sans préavis, et SPINCV ne sera pas responsable de toute suspension ou résiliation, y compris de ses conséquences. SPINCV se réserve le droit de supprimer tout message avec .ade, .adp, .bat, .chm, .cmd, .com, .cpl, .exe, .hta, .ins, .isp, .jar, .jse,. lib, .lnk, .mde, .msc, .msp, .mst, .pif, .scr, .sct, .shb, .sys, .vb, .vbe, .vbs, .vxd, .wsc, .wsf, .wsh, ou .zip pièce jointe pour n'importe quelle raison ou aucune.
         </p>
                            <br />
                            <p><strong>III. Conditions supplémentaires applicables aux employeurs</strong><br /><br />
            Les employeurs sont les seuls responsables de leurs publications sur le site. SPINCV ne doit pas être considéré comme un employeur en ce qui concerne votre utilisation du site et le site ne sera pas responsable de toute décision d'emploi, pour quelque raison que ce soit, faite par toute entité affichant des emplois sur le site.<br />
            Vous comprenez et reconnaissez que si vous annulez votre compte employeur ou votre compte employeur sera résilié, toutes vos informations de compte sur le site, y compris les CV, les contacts réseau et les listes de diffusion électroniques, seront marqués comme supprimés et peuvent être supprimés des bases de données du site. Les informations peuvent continuer à être disponibles pendant un certain temps en raison de retards dans la propagation de ces suppressions via les serveurs Web du site.<br />
            Afin de protéger nos Utilisateurs de la publicité commerciale ou de la sollicitation, nous nous réservons le droit de restreindre le nombre de courriels qu'un Employeur peut envoyer aux Utilisateurs à un nombre que nous jugeons approprié à notre seule discrétion.<br />
            Les profils de candidats dérivés du contenu de l'utilisateur peuvent également être mis à disposition sur le site. SPINCV ne fait aucune représentation concernant l'exactitude ou la validité de ces travaux dérivés ou leur pertinence pour l'évaluation par les employeurs. Les profils dérivés peuvent varier considérablement du contenu utilisateur.
         </p>
                            <br />
                            <p><strong>IV. Conditions supplémentaires applicables aux demandeurs d'emploi.</strong><br /><br />
            Lorsque vous vous inscrivez sur le site, il vous sera demandé de créer un compte et de fournir au site certaines informations, y compris d'une adresse courriel valide (vos "informations").<br />
            Tout profil que vous soumettez doit être exact et vous décrire en tant qu'une personne individuelle. Le profil exige que les champs standard soient complétés. Lorsque vous fournissez des informations de contact SpinCV (telles que votre nom et votre adresse courriel) et des informations démographiques, vous acceptez que SpinCV puisse utiliser ces informations comme indiqué dans les présentes. Vous acceptez que SpinCV puisse, dans le cadre de ses services, communiquer avec vous ou initier une communication avec vous pour le compte d'un tiers, via votre compte SpinCV ou par d'autres moyens tels que courrier électronique, téléphone (y compris téléphone portable) ou courrier postal, y compris par l'utilisation des informations de contact que vous pouvez fournir à SpinCV ou que SpinCV peut obtenir de ressources tierces. Si et dans la mesure permise par la loi applicable, SpinCV ou ses partenaires tiers désignés peuvent également utiliser Vos informations de contact pour (i) vous envoyer des alertes, (ii) créer un compte et (iii) vous envoyer des informations sur SpinCV, y compris Matériel promotionnel. SpinCV peut utiliser des données démographiques et/ou de profil pour personnaliser votre expérience sur le Site, vous montrer du contenu qui pourrait vous intéresser et afficher du contenu selon vos préférences. Vos informations, y compris vos informations personnelles, sont placées sur le site lorsque vous téléchargez ou modifiez un CV. Dans la mesure où vous téléchargez un CV ou le modifiez, et sous réserve de vos paramètres de confidentialité, vous fournissez le CV, votre nom et d'autres informations personnelles sur votre CV à des tiers qui pourraient vous intéresser en tant qu'employé ( et qui peuvent transmettre votre CV et vos renseignements personnels à d'autres tierces parties), aux chercheurs d'emploi qui pourraient vouloir vous contacter, aux moteurs de recherche ou au grand public en affichant vos renseignements personnels sur Internet.<br />
            Vous reconnaissez et acceptez que vous êtes seul responsable de la forme, du contenu et de l'exactitude de tout résumé ou matériel qui y est placé par vous sur le site.<br />
            Vous reconnaissez et acceptez qu'il vous appartient de vérifier quels Employeurs reçoivent votre CV lorsque vous avez autorisé SPINCV à envoyer votre CV en votre nom. Vous reconnaissez et acceptez que SPINCV peut utiliser les paramètres de votre compte d'utilisateur pour envoyer des CV aux employeurs en votre nom, et que nous pouvons modifier la mise en forme de votre CV avant de l'envoyer aux employeurs. Vous dégagez expressément SPINCV de toute responsabilité pour tout dommage, tant pécuniaire que non pécuniaire, résultant de votre défaut d'examiner vos destinataires de CV.<br />
            SPINCV se réserve le droit de vous offrir des services et des produits tiers en fonction des préférences que vous identifiez dans votre inscription et à tout moment par la suite ou que vous avez accepté de recevoir. Ces offres peuvent être faites par le site ou par des tiers. S'il vous plaît, voir la politique de confidentialité pour plus de détails concernant vos informations.<br />
            Vous comprenez et reconnaissez que vous n'avez aucun droit de propriété sur votre compte et que si vous annulez votre compte ou votre compte est résilié, toutes vos informations de compte sur le site, y compris CV, profils, lettres de motivation, travaux sauvés, questionnaires seront marqués comme supprimé et peuvent être supprimé des bases de données du Site et seront supprimé de toute zone publique du Site. Les informations peuvent continuer à être disponibles pendant un certain temps en raison de retards dans la propagation de ces suppressions via les serveurs Web du site. En outre, des tiers peuvent conserver des copies sauvegardées de Vos informations.<br />
            Le site se réserve le droit de supprimer votre compte et toutes vos informations après une longue période d'inactivité.
         </p>
                            <br />
                            <p><strong>V. Contenu de l'utilisateur</strong><br /><br />
            Certaines parties du site, telles que les forums et les forums, peuvent permettre aux utilisateurs d'afficher des offres d'emploi, des curriculums vitae, des informations, du texte, des images, des fichiers audios, des vidéos, des messages et d'autres éléments., ou autrement mis à disposition sur ou via le Site est appelé "Contenu Utilisateur" dans le présent document. Une telle fonctionnalité est conçue pour aider les utilisateurs à obtenir des informations sur leur carrière et leur entreprise, à faciliter la communication, à discuter des moyens de prendre des décisions de carrière et à informer les utilisateurs des emplois. Le contenu utilisateur est fourni par des contributeurs tiers, dont beaucoup peuvent utiliser des pseudonymes anonymes. Le contenu de l'utilisateur peut être inexact, incomplet, trompeur. Par exemple, le site héberge des pages d'employeur, qui permettent au contenu utilisateur d'être publié par des personnes qui ne sont pas affiliées à l'employeur propriétaire de la page employeur, y compris les réponses aux questions sur les pages employeur. SPINCV ne cautionne pas et n'est pas responsable de tout contenu utilisateur, y compris les opinions, conseils, informations ou déclarations qui y sont contenus. Vous reconnaissez qu'en accédant au site, vous pouvez entrer en contact avec du contenu (y compris du contenu utilisateur) que vous pouvez trouvez nuisible, offensant, menaçant, indécent ou répréhensible, y compris, un langage explicite et d'autres contenus potentiellement offensants. Reconnaissant que SPINCV n'a aucune responsabilité à l'égard de ce contenu. En outre, vous accordez à SpinCV, à ses sociétés affiliées et à ses sous-licenciés la licence d'utilisation de votre nom, nom d'utilisateur, photographies et/ou marques et logos en relation avec tout Contenu Utilisateur ou matériel marketing de SpinCV, y compris publier sur le site, ou des actions de SpinCV pour promouvoir ou publiciser un tel contenu d'utilisateur, y compris l'utilisation de mots-clés dans les moteurs de recherche Internet tiers.<br />
            Vous ne devez pas publier de Contenu Utilisateur illégal, frauduleux, discriminatoire, menaçant, abusif, diffamatoire, obscène ou répréhensible, ou qui contient des propos sexuels, ethniques, raciaux ou autres, ou qui ne contient aucun contenu pertinent ou constructif. Vous ne devez pas publier de Contenu Utilisateur contenant des informations confidentielles, des secrets commerciaux, des informations confidentielles, des publicités, des sollicitations, des chaînes de lettres, des systèmes pyramidaux, des opportunités d'investissement ou toute autre communication commerciale non sollicitée ou encourager ou provoquer le pourriel ou l'inondation.<br />
            Il vous est interdit d'afficher tout contenu d'utilisateur contenant des informations d'identification officielles (comme la vôtre ou d'une autre personne), tels le numéro d'identification sociale, numéro de passeport, numéro d'identification national, numéro d'assurance, numéro de permis de conduire, numéro d'immigration ou tout autre numéro similaire , code ou identifiant. L'affichage de ces informations d'identification peut entraîner un vol d'identité et d'autres conséquences néfastes. SPINCV peut supprimer toute information d'identification de ce type, mais n'assume aucune obligation de le faire, et décline toute responsabilité en cas de publication de ces informations d'identification. SPINCV se réserve le droit de modifier l'affichage de CV sur son Site, y compris, de masquer des champs, de réorganiser son format et de changer les éléments visuels.<br />
            Bien que SPINCV n'ait aucune obligation de le faire, SPINCV peut surveiller le Contenu Utilisateur et se réserve le droit de supprimer tout Contenu Utilisateur ou partie de Contenu qui, à la seule discrétion de SPINCV, viole les règles ci-dessus, y compris tout Contenu Utilisateur non lié à la partie spécifique du Site sur lequel il est posté, ou qui est une publicité, un message de recrutement ou un autre message publicitaire, ou que SPINCV juge à sa seule discrétion comme étant inapproprié. Si vous estimez qu'un Contenu Utilisateur viole le présent Contrat ou nos règles, veuillez contacter immédiatement SPINCV afin que nous puissions envisager d'en supprimer. Pour plus de clarté, SPINCV n'a aucune obligation de supprimer tout Contenu Utilisateur, et de tout Contenu Utilisateur qui viole toute politique SPINCV se rapportera à la seule discrétion de SPINCV.<br />
            SPINCV se réserve le droit de divulguer tout Contenu Utilisateur et autres informations pertinentes, ainsi que les circonstances entourant leur transmission, à tout tiers en relation avec l'exploitation du Site; pour protéger, ses affiliés, ses partenaires et ses visiteurs, ainsi que le Site; et pour se conformer aux obligations légales ou aux demandes gouvernementales. Cela signifie, par exemple, que SPINCV peut honorer les citations à comparaître, les mandats de perquisition, les demandes d'application de la loi ou les demandes des tribunaux pour révéler l'adresse électronique et l'identité d'un utilisateur, ou toute autre information demandée. En tant qu'employeur, lorsque vous publiez une annonce pour un emploi sur SPINCV (ci-après "Job List") que vous choisissez de classer comme confidentiel, votre identité peut être découverte sur demande du gouvernement ou de l'application de la loi.<br />
            Sans limiter la généralité de ce qui précède, SPINCV se réserve le droit (mais n'est pas obligé) de supprimer toute offre d'emploi qui discrimine directement ou indirectement les demandeurs d'emploi. La discrimination directe signifie, par exemple, qu'une liste d'emplois indique clairement que seuls les demandeurs d'emploi correspondant à certains critères sont recherchés, excluant ainsi d'autres en raison, par exemple, de leur sexe, race, âge ou handicap. La discrimination indirecte signifie, par exemple, qu'une liste d'emplois exclut implicitement certaines catégories de chercheurs d'emploi en les empêchant de se qualifier pour les exigences du poste. Vous comprenez et acceptez qu'il vous incombe de vous abstenir d'afficher toute offre d'emploi qui discrimine directement ou indirectement les demandeurs d'emploi ou enfreint les lois en vigueur.
         </p>
                            <br />
                            <p><strong>VI. Politique de communication</strong><br /><br />
            Sans limiter la généralité de la politique de contenu utilisateur ci-dessus, en tant qu'utilisateur du site, vous reconnaissez que les utilisateurs peuvent échanger des messages et des courriels entre eux. En tant qu'utilisateur, vous reconnaissez et acceptez de vous conformer aux règles décrites dans cette section de ce Contrat, ci-après la "Politique de communication".<br />
            En tant que demandeur d'emploi ou autre utilisateur du site, vous ne devez envoyer aucun message via le Site ou par courriel à un autre Utilisateur ou Employeur qui n'est pas directement lié à votre recherche d'emploi. Sans limiter la généralité de ce qui précède, vous ne devez envoyer à aucun autre Utilisateur ou Employeur des sollicitations commerciales pour des produits ou services, ou tout autre message pouvant être considéré comme pourriel ou autre message ou courriel non sollicité.<br />
            En tant qu'employeur, vous ne devez envoyer aucun message via le site via les services ou par courriel à un autre utilisateur ou demandeur d'emploi qui n'est pas directement lié aux emplois de votre entreprise ou des offres d'emploi affichées.<br />
            SPINCV se réserve le droit de surveiller toute communication envoyée via le Site afin d'évaluer les violations potentielles de cette Politique de communication. SPINCV se réserve le droit de suspendre ou de résilier le compte de tout Utilisateur qui enfreint la Politique de Communication, et/ou de résilier le présent Contrat entre l'Utilisateur et SPINCV. SPINCV ne sera pas responsable envers Vous ou un tiers pour tout dommage, pécuniaire ou non pécuniaire, résultant de communications (ou de leur contenu, ou de leurs pièces jointes) envoyées via le Site ou par courriel, que ce soit en violation des Communications politiques ou non. Vous serez seul responsable des communications envoyées via le Site ou par courriel, et SPINCV décline toute responsabilité à cet égard.
         </p>
                            <br />
                            <p><strong>VII. Honoraires</strong><br /><br />
            En tant que demandeur d'emploi, vous pouvez acheter des forfaits pour certains services disponibles sur le site ("services complémentaires"), comme décrit plus en détail sur notre page de prix. Tous les montants sont en dollars américains, sauf indication contraire. Les employeurs peuvent également effectuer certains achats de services complémentaires sur le site. Les taxes applicables peuvent être ajoutées au moment de la commande, en fonction de votre emplacement. Tous les achats ne sont pas remboursables, et tous les services complémentaires doivent être utilisés dans un délai d'un (1) an suivant l'achat, faute de quoi ils seront perdus. Toutes les politiques concernant les prix ou les paiements affichés sur la page de prix ou sur toute autre page du site sont juridiquement contraignantes et incorporées par référence dans le présent accord.<br />
            Tous les frais payés via le Site sont traités via une connexion https: // sécurisée, et le traitement des paiements est géré par le processeur de paiement en ligne Adyen. Stripe accepte les cartes Visa, MasterCard et American Express comme options de paiement, mais celles-ci sont sujettes à changement sans préavis. Une fois que les transactions sont acceptées par Stripe, elles sont traitées conformément aux règles et procédures du programme de Stripe et aux conditions d'utilisation. SPINCV et les processeurs de paiement sont des sociétés non affiliées et SPINCV n'a aucune influence sur les opérations des processeurs de paiement. SPINCV ne pourra en aucun cas être tenu pour responsable des pertes ou dommages, directs ou indirects, pécuniaires ou autres, résultant d'une erreur ou d'une défaillance de la part des entreprises de traitement des paiements.
         </p>
                            <br />
                            <p><strong>VIII. Exclusion de garantie</strong><br /><br />
            SPINCV décline toute responsabilité quant à l'exactitude, le contenu, l'exhaustivité, la légalité, la fiabilité, l'opérabilité ou la disponibilité des informations ou documents affichés ou liés aux résultats de recherche SPINCV (y compris les offres d'emploi) ou mis à disposition sur le site par SPINCV ou des tiers (y compris le contenu utilisateur), qu'ils soient payés ou utilisés gratuitement. SPINCV décline toute responsabilité quant à l'exactitude, le contenu, l'exhaustivité ou la fiabilité des informations fournies par SPINCV à des fins d'information uniquement. Vous reconnaissez que vous ne payez pas SPINCV pour les informations susmentionnées. SPINCV décline toute responsabilité pour la suppression, le défaut de stockage, la mauvaise livraison, ou la livraison intempestive de toute information, courriel ou matériel (y compris le contenu de l'utilisateur). SPINCV décline en outre toute responsabilité pour tout dommage résultant du téléchargement ou de l'accès à toute information ou matériel sur le site ou sur d'autres sites ou services sur l'Internet accessible par l'intermédiaire du site. SPINCV ne pourra en aucun cas être tenu responsable envers Vous ou un tiers en raison de Votre utilisation ou de l'utilisation abusive ou de la dépendance du Site. De plus, SPINCV ne peut en aucun cas être tenu responsable envers Vous ou un tiers en raison de votre utilisation ou de votre utilisation abusive ou de votre dépendance à l'égard de tout site ou service tiers que vous liez à partir du Site.<br />
            SPINCV décline toute responsabilité pour tout dysfonctionnement technique du Site, y compris tout réseau ou service téléphonique, systèmes informatiques, serveurs ou fournisseurs, équipement informatique ou de téléphonie mobile, logiciel, échec de livraison de courrier électronique, ouverture de compte, ou tout autre service fourni par SPINCV à la suite de problèmes techniques ou d'embouteillages sur Internet ou tout autre site Web tiers ou combinaison de ceux-ci, y compris les blessures ou dommages à Votre ordinateur ou à tout ordinateur, appareil mobile ou autre matériel ou logiciel d'une autre personne ou résultant de l'utilisation ou du téléchargement de tout Contenu en relation avec le Site ou les services. SPINCV ne sera en aucun cas responsable de toute perte ou dommage à tout contenu ou blessure ou décès résultant de l'utilisation du Site, des services, du Contenu Utilisateur ou des applications tierces, des sites Web, des logiciels ou du contenu publié sur ou via le Site ou transmis aux utilisateurs ou toute interaction entre les utilisateurs du Site ou des services, que ce soit en ligne ou hors-ligne.<br />
            LE SITE ET TOUS LES MATÉRIAUX, INFORMATIONS, CONSEILS, GUIDE DE CARRIÈRE, CONTENU UTILISATEUR, PRODUITS ET SERVICES DISPONIBLES SUR OU SUR LE SITE SONT FOURNIS "EN L'ÉTAT", SANS AUCUNE GARANTIE, EXPRESSE OU IMPLICITE. SPINCV ET SES SOCIÉTÉS AFFILIÉES, ET SES CONCÉDANTS ET LEURS TIERS, DÉCLINENT EXPRESSÉMENT DANS TOUTE LA MESURE AUTORISÉE PAR LA LOI TOUTE GARANTIE EXPRESSE, IMPLICITE, LÉGALE OU AUTRE, Y COMPRIS, SANS LIMITATION, LES GARANTIES DE QUALITÉ MARCHANDE, D'ADÉQUATION À UN USAGE PARTICULIER ET NON-INFRACTION AUX DROITS DE PROPRIÉTÉ. SPINCV ET SES SOCIÉTÉS AFFILIÉES, ET SES CONCÉDANTS ET LEURS TIERS, DÉCLINENT TOUTE GARANTIE CONCERNANT LA SÉCURITÉ, LA FIABILITÉ, L'OPPORTUNITÉ ET LA PERFORMANCE DU SITE, ET TOUT MATÉRIEL, INFORMATION, CONSEIL, LISTE DE JOBS, CONTENU UTILISATEUR, PRODUITS ET SERVICES DISPONIBLES SUR: OU À TRAVERS LE SITE. SPINCV ET SES SOCIÉTÉS AFFILIÉES, ET SES CONCÉDANTS ET LEURS CONCÉDANTS DE LICENCE TIERS, DÉCLINENT TOUTE GARANTIE CONCERNANT LES SERVICES OU MARCHANDISES REÇUS OU PUBLIÉS SUR LE SITE OU REÇUS PAR L'INTERMÉDIAIRE DE TOUT LIEN MIS À DISPOSITION PAR SPINCV.<br />
            VOUS COMPRENEZ ET ACCEPTEZ QUE VOUS TÉLÉCHARGEZ OU OBTENEZ AUTREMENT DU MATÉRIEL OU DES DONNÉES PAR L'UTILISATION DU SITE À VOTRE PROPRE DISCRÉTION ET À VOTRE RISQUE ET QUE VOUS SEREZ LE SEUL RESPONSABLE DE TOUT DOMMAGE À VOTRE SYSTÈME INFORMATIQUE OU DE TOUTE PERTE DE DONNÉES RÉSULTANT DU TÉLÉCHARGEMENT OU DE L'OBTENTION TELS MATÉRIAUX OU DONNÉES.
         </p>
                            <br />
                            <p><strong>IX. Déni de responsabilité</strong><br /><br />
            Le site sert, entre autres, (i) aux employeurs de publier des offres d'emploi, de rechercher et d'évaluer des candidats et (ii) aux candidats d'afficher des CV et des profils et de rechercher et évaluer des offres d'emploi. SPINCV ne filtre ni ne censure les listes, y compris les profils proposés. SPINCV n'est pas impliqué et ne contrôle pas la transaction entre employeurs et candidats, ni aucune communication entre eux. Par conséquent, SPINCV n'est pas responsable du contenu de l'utilisateur, de la qualité, de la sécurité ou de la légalité des emplois ou des CV publiés, de la véracité ou de l'exactitude des annonces, de la possibilité des employeurs de proposer des offres d'emploi ou l'opportunité aux candidats d'adhérer aux offres d'emploi. SPINCV ne fait aucune déclaration sur les offres d'emploi, CV ou Contenu Utilisateur sur le Site. Bien que SPINCV se réserve le droit, à sa seule discrétion, de supprimer quand il le souhaite le Contenu Utilisateur, les offres d'emploi, les CV ou autres éléments du Site. SPINCV n'assume aucune obligation de le faire et dans la mesure permise par la loi, décline toute responsabilité pour ne pas avoir pris une telle mesure.<br />
            Notez qu'il existe des risques, y compris, sans limitation, le risque de préjudice physique, de traiter avec des étrangers, des personnes mineures ou des personnes agissant sous de faux prétextes. Vous assumez tous les risques associés aux relations avec les autres utilisateurs avec lesquels vous entrez en contact via le Site. De par sa nature même, l'information d'autrui peut être offensante, nuisible ou inexacte, et dans certains cas, mal étiqueté ou trompé. Nous nous attendons à ce que vous utilisiez la prudence et le bon sens lors de l'utilisation du site.<br />
            Parce que l'authentification de l'utilisateur sur Internet est difficile, SPINCV ne peut pas et ne confirme pas que chaque utilisateur de ce qu'ils prétendent être. Parce que nous ne pouvons pas et ne pouvons pas être impliqués dans des transactions d'utilisateur à utilisateur ou contrôler le comportement des participants sur le site, dans le cas où vous avez un différend avec un ou plusieurs utilisateurs, vous libérez SPINCV (et nos agents et employés) de réclamations, demandes et dommages (réels et indirects et directs et indirects) de toute nature, connus et inconnus, suspectées et insoupçonnés, divulgués et non divulgués, découlant de ou liés de quelque manière que ce soit à ces différends dans toute la mesure permise par la loi .<br />
            Le site et le contenu peuvent contenir des inexactitudes ou des erreurs typographiques. SPINCV ne fait aucune déclaration quant à l'exactitude, la fiabilité, l'exhaustivité ou l'actualité du Site ou du Contenu. L'utilisation du Site et du Contenu est à vos risques et périls. Des modifications sont apportées périodiquement au Site et peuvent être effectuées à tout moment. SPINCV ne peut garantir et ne promet aucun résultat spécifique lié à l'utilisation du Site. Aucun conseil ou information, oral ou écrit, obtenus par un Utilisateur de SPINCV ou par le biais ou à partir de tout Site ne pourra créer une quelconque garantie non expressément mentionnée ici.<br />
            SPINCV vous encourage à conserver une copie de sauvegarde de votre contenu utilisateur. Dans la mesure permise par la loi, SPINCV ne peut en aucun cas être tenu responsable de la suppression, de la perte ou de la modification non autorisée de tout Contenu Utilisateur.<br />
            SPINCV ne fournit ni ne fait aucune déclaration quant à la qualité ou à la nature des produits ou services de tiers achetés sur le Site, ni à toute autre représentation, garantie ou garantie. Un tel engagement, représentation, garantie ou sous garantie serait fourni uniquement par le fournisseur de ces produits ou services tiers, selon les termes convenus par le fournisseur.<br />
            Si vous croyez que quelque chose sur le site enfreint cet accord, veuillez contacter notre agent désigné comme indiqué dans la section 6 ci-dessus.<br />
            En cas de notification de tout contenu ou autre matériel qui ne serait pas conforme au présent Contrat, SPINCV peut, à sa seule discrétion, enquêter sur l'allégation et décider de supprimer ou de demander la suppression du contenu. SPINCV n'a aucune responsabilité vis-à-vis des Utilisateurs pour l'exécution ou la non-exécution de telles activités.
         </p>
                            <br />
                            <p><strong>X. Terme et résiliation.</strong><br /><br />
            Cet accord restera en vigueur et de plein effet lorsque vous êtes un utilisateur du site. SPINCV se réserve le droit, à sa seule discrétion, de poursuivre tous ses recours légaux, y compris, mais sans s'y limiter, la suppression de votre Contenu Utilisateur du Site et la résiliation immédiate de Votre inscription ou votre capacité à accéder au Site et/ou à tout autre service fourni par SPINCV, en cas de violation par vous de cet accord ou si SPINCV est incapable de vérifier ou d'authentifier toute information que vous soumettez à l'enregistrement du site.
         </p>
                            <br />
                            <p><strong>XI. Général</strong><br /><br />
            La présente entente est régie par les lois de fond internes de la province de Québec, Canada, sans égard à ses principes de conflit de lois. La compétence pour toute réclamation découlant de la présente entente incombe exclusivement aux tribunaux compétents du district judiciaire de Montréal, province de Québec. Si une disposition du présent Accord est jugée invalide par un tribunal compétent, la nullité de cette disposition n'affectera pas la validité des autres dispositions du présent Accord, qui restera en vigueur et de plein effet. Aucune renonciation à l'une ou l'autre des dispositions du présent contrat ne sera considérée comme une renonciation supplémentaire ou continue de ce terme ou de toute autre modalité. En outre, l'incapacité de SPINCV à appliquer toute clause de ce Contrat ne sera pas considérée comme une renonciation à ce terme ou affectera autrement la capacité de SPINCV à faire appliquer ce terme à tout moment dans le futur.<br />
            Le présent Contrat en conjonction avec la Politique de confidentialité constitue l'intégralité de l'accord entre les parties en ce qui concerne l'objet des présentes et remplace tous les accords ou accords antérieurs ou contemporains, écrits ou oraux, concernant un tel sujet. Lorsque vous avez effectué un achat, vous êtes également soumis aux termes et conditions de tout tiers de Processeur de paiement utilisé pour effectuer l'achat. Toute renonciation à toute disposition du présent Contrat ne sera effective que si elle est écrite et signée par SPINCV. Ce Contrat, ainsi que les modifications et les accords supplémentaires que vous pouvez conclure avec SPINCV en relation avec le Site, constituent l'intégralité de l'accord entre vous et SPINCV concernant le Site. Si une disposition du présent Accord est jugée invalide par un tribunal compétent, l'invalidité de cette disposition n'affectera pas la validité des autres dispositions du présent Accord, qui restera en vigueur et de plein effet. Vous acceptez que le présent Contrat ne puisse pas être modifié, modifié, modifié ou annulé, sauf par un document signé par un représentant autorisé de chaque partie. Afin d'éviter toute ambiguïté, les communications par courriel ou par téléphone entre Vous et un employé de SPINCV ne constitueront pas une modification ou une modification du présent Contrat.<br />
            En accédant ou en utilisant le site, vous signifiez votre consentement à cet accord et acceptez de vous conformer à toutes les lois et règlements applicables, y compris les lois et règlements canadiens sur le contrôle des exportations et des réexportations, les droits d'auteur et autres lois sur la propriété intellectuelle.<br />
            Vous comprenez et reconnaissez que SPINCV ou ses sociétés affiliées, ou ses concédants de licence possèdent tous les droits et intérêts sur le Site et tous les droits de propriété qui y sont associés. SPINCV se réserve tous les droits non spécifiquement accordés aux présentes. Vous ne devez pas modifier les avis de droits d'auteur, les mentions exclusives, les marques de commerce et les marques de service, les marques de brevet ou autres marques de propriété sur les documents consultés sur le site, autres que votre contenu utilisateur. Toute utilisation de matériaux ou de descriptions, toute utilisation dérivée du Site ou de ses matériaux, et toute utilisation d'exploitation de données, de robots ou d'outils similaires de collecte et d'extraction de données sont strictement interdites. En aucun cas, Vous ne pouvez encadrer une partie du Site ou des éléments qui y sont contenus.<br />
            Toute notification adressée à SPINCV doit être envoyée par courrier recommandé ou par avion ou par courrier express. La notification peut être effectuée en envoyant un courrier électronique à l'adresse courriel indiquée sur votre compte ou en envoyant un message à votre adresse d'interface de compte, et il est considéré reçu lors de l'envoi (pour le courriel) ou pas plus de quinze (15) jours après avoir été posté.<br />
            Vous ne pouvez céder ou déléguer aucun de vos droits ou obligations ci-dessous sans le consentement écrit préalable de SPINCV et toute tentative de ce type sera nulle. SPINCV peut librement céder ou déléguer ses droits et obligations en vertu des présentes sans préavis. En outre, SPINCV peut céder tout accord entre vous et SPINCV à toute entité SPINCV liée en vous informant de cette cession. SPINCV et vous n'êtes pas des partenaires ou agents légaux, mais des entrepreneurs indépendants.<br />
            SPINCV ne sera pas responsable de tout manquement à ses obligations en vertu du présent Contrat si une telle défaillance résulte d'un contrôle raisonnable de SPINCV, y compris, mais sans s'y limiter, a une défaillance ou une dégradation mécanique, électronique ou de communication ou tout cas de force majeure.<br />
            Les parties reconnaissent avoir expressément exigé que le présent contrat et la politique de confidentialité soient rédigés en anglais. <i>Les parties présentes reconnaissent avoir expressément exigé que les présentes Conditions d'utilisation et la Politique de confidentialité soient rédigées en anglais.</i>
                            </p>

                        </div>
                    </div>
                </Fragment>
            </Layout>
        )
    }
}

export default TermConditions;